### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by okdistribute** [digidem/mapeo-core#74]
Do we know why the tests are failing?

**Comment by noffle** [comment]
Only `^8.1.0` is failing, not `^9.0.0`. The breakage was introduced by 192b4e8c041a34b81e8981da6f5c99c4a12299d3. Hypercore8 can handle different project keys, but Hypercore7 can't. This is breaking a test that uses a mapeo-core /w a project key, and a syncfile /wo a project key.

I'm working on a fix.

**Comment by noffle** [comment]
I had to rerun some tests in Travis, but [they're passing](https://travis-ci.org/digidem/mapeo-core/builds/647576659) now.

The fix was in the tests, so a new release isn't required.

The tests are still pretty flaky, since those fixes are only in https://github.com/digidem/mapeo-core/pull/49 and will only be merged into `master` (`^9.0.0`).

**Comment by okdistribute** [comment]
awesome thanks !!
